name: CustomBar
author: SuperKali
version: 0.9
api:
- '2.0.0'
- '3.0.0-ALPHA4'
- '3.0.0-ALPHA5'
- '3.0.0-ALPHA6'
main: CustomBar\Main
description: Custom bar for your server!
github: https://github.com/SuperKali/CustomBar
